name: ectocervix_chronic_hiv

channels:
 - bioconda
 - conda-forge
 - defaults
 - r
 - psi4

dependencies:
 - r-base=4.1.3
 - rstudio-desktop=2022.12.0
 - bioconductor-fgsea=1.20.0
 - bioconductor-edger=3.36.0
 - r-biocmanager
 - r-remotes
 - r-igraph
 - r-pheatmap=1.0.12
 - r-rcolorbrewer
 - r-scales
 - r-rafalib
 - r-enrichR=3.1
 - r-matrix
 - r-rmarkdown
 - r-xlsx
 - r-readxl
 - r-bookdown
 - compilers
